#
# status.sh
#

declare -Ag SEASHELL_ERROR_STATUS=(
    ["SYSTEM_SHELL_UNSUPPORT"]=10
    ["SYSTEM_DISTRIBUTION_UNSUPPORT"]=11
    ["FILE_NONEXISTENT"]=44
    ["PACKAGE_NOT_FOUND"]=54
    ["PACKAGE_NAME_INVALID"]=57
    ["FUNCTION_NAME_INVALID"]=67
    ["FUNCTION_NAME_FORBIDDEN"]=69
    ["VARIABLE_INVALID"]=77
    ["KEY_NAME_INVALID"]=117
    ["PARAMETER_VALUE_INVALID"]=124
    ["PARAMETER_TOO_MANY"]=125
    ["PARAMETER_MISSING"]=126
    ["UNKNOWN"]=127
)
